services:
  servidor:
    container_name: BackendRevisao
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on: 
      - db 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/revisao_automotiva
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create    
    networks: 
      - backend
  db:
    container_name: PostgreSQLRevisao
    image: 'postgres:13.4-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=revisao_automotiva
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - backend  
volumes:
  db-data:

networks:
  backend: